### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by krrisztian** [krrisztian/QuoteSite#4]
The Raleway font is great tho.
Do we have to use all-caps? the "about" text looks great in non-caps....lets see not all caps

**Comment by krrisztian** [comment]
Maybe some other font??

**Comment by krrisztian** [comment]
Möglichkeiten:

[Karla](https://fonts.google.com/specimen/Karla
):  caps/nicht caps

[Comfortaa](https://fonts.google.com/specimen/Comfortaa
): nicht caps

[Yantramana](https://fonts.google.com/specimen/Yantramanav
): caps/nicht caps

[Hind](https://fonts.google.com/specimen/Hind+Siliguri): caps

**Comment by KaiSMR** [comment]
Stayed with Raleway
using no caps anymore
use font-weight: 600 for author
added letter spacing for quote
